# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170225_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.CharField(default='desc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='desc2', max_length=500),
            preserve_default=False,
        ),
    ]
