# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170226_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='images', upload_to='polls/media'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
