# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170226_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
