# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170226_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='static/polls/media'),
        ),
    ]
