# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170226_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='polls/media')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.AddField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='polls.Question'),
        ),
    ]
